version: "3.7"

services:
  db:
    container_name: db
    image: postgres:17
    env_file:
      - .env
    restart: always
    expose:
      - "${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrator:
    container_name: migrator
    image: migrate/migrate
    env_file:
      - .env
    volumes:
      - ./migrations:/migrations
    depends_on:
      db:
        condition: service_healthy
    command: -path=/migrations -database postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable up

  app:
    container_name: app
    image: antgoncharik/crypto-knight-history
    env_file:
      - .env
    volumes:
      - .env:/opt/app/.env:ro
    restart: always
    depends_on:
      migrator:
        condition: service_completed_successfully
    expose:
      - "${APP_SERVER_PORT}"

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      app:
        condition: service_started

volumes:
  db-data:
